sudo: false
language: node_js
node_js:
  - "stable"
  services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE retsy;" -U postgres
  - psql -c "CREATE USER ibrahim WITH PASSWORD '121203';" -U postgres
script: npm run test
nofications: 
  email: false
